version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - go build hello.go
  post_build:
    commands:
      - git clone https://github.com/vaddy/go-vaddy.git
      - cd ./go-vaddy/bin/
      - chmod 700 vaddy-linux-64bit
      - ./vaddy-linux-64bit
      - echo Build completed on `date`
