version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - go build hello.go
  post_build:
    commands:
      - wget https://github.com/vaddy/go-vaddy/blob/master/bin/vaddy-linux-64bit
      - chmod 700 vaddy-linux-64bit
      - ./vaddy-linux-64bit
      - echo Build completed on `date`
